### ISSUE TITLE
align the header and footer style with blog

### ISSUE THREAD

**Issue by ll911** [bcgov/data-fp#32]
align the header and footer style with blog
https://blog.data.gov.bc.ca/

**Comment by ll911** [comment]
see requirement in https://github.com/bcgov/ckanext-bcgov/issues/82

**Comment by gjlawran** [comment]
Review with ED and others. Confirm design changes to match.

**Comment by gjlawran** [comment]
Review

**Comment by ll911** [comment]
https://github.com/bcgov/ckanext-bcgov/issues/82
