### ISSUE TITLE
Ideas for next release

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/data-fp#35]
These are some ideas to improve the data.gov webpage for users.

motivation: https://www.apple.com/macos/sierra-preview/

Header
reduce the size of the header (see issue #32)

Carousel
Having to click on the arrows which are on either end is a bit cumbersome, and it takes some time to find the visualization you're looking for. To improve the user experience the carousel should be removed entirely and replaced with a 'single page' type experience, where the visualizations appear below each other and occupy the full page.
This will also provide more space for upcoming visualizations which won't fit in the limited space of the current carousel window. We'll just have to make sure scrolling is not used in the viz to prevent interaction with the viz when the user is trying to scroll down the page.

Text boxes below the carousel

Generally there is too much text here. Having 3 'Most popular..' sections feels sloppy and unnecessary. The popular sections should be combined to a single top 5 list. 

Twitter Feed
This should match the feed used in https://blog.data.gov.bc.ca/

**Comment by ll911** [comment]
few ideas.
- single page
- full page and full screen option for data visualization 
- transition between visualization 
- auto hide header/footer when scrolling

**Comment by gjlawran** [comment]
- Replicate the header from the catalogue.
- Drop the search magnify glass from the header.
- Move the main menu into the hamburger on mobile.
- Auto hide the ribbon and shrink the header when scroll down, leave more room for the body
-  Materialized the featureboxes, carousel them in mobile mode.
- Transparent the visualizations with background transitions
- Remove hamburger in full page - and add standard GSA search
- Include an icon with hover to the viz code
- add a link to share visualizations using social media
- move arrows on carousel closer to the viz, like main gov site
- have carousel cycle automatically, but stop if the mouse if over the current iframe.
- Hyperlink the DataBC Header to http://www2.gov.bc.ca/gov/content/governments/about-the-bc-government/databc
- add version number and Git Hash 

Background resources:
http://www2.gov.bc.ca/gov/content/about-gov-bc-ca/web-presence/developers-guide
