### ISSUE TITLE
Need to redo header to match blog site

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/data-fp#37]
@h3devin are you available to update the header of data.gov.bc.ca to match this
http://engage.gov.bc.ca/data/ ?

@ll911 can we simply replace the ribbon items on the blog with what we have on our data.gov site?

**Comment by ll911** [comment]
blog has no ribbon in mobile, i would suggest no ribbon at all like main bcgov site. bcdc ribbon needs updated as well with new blog link and including site/data usage link like UK open data portal.

**Comment by Mbrownshoes** [comment]
@leo okay, we'll go with the main gov header when it is reduced with no items displayed, like so:
![screen shot 2017-02-28 at 1 53 25 pm](https://cloud.githubusercontent.com/assets/3362533/23435813/476b2962-fdbd-11e6-8eda-ceea8d53c50d.png)

These would be visible when clicking on the hamburger:
What is DataBC?	Data Catalogue	Geographic Services	Blog	Developers	Contact

**Comment by h3devin** [comment]
@Mbrownshoes 

Just making sure I understand what you're after...

- You'd like the data.gov.bc.ca site to hide the search/menu icon when in a desktop mode, and instead show a search bar (probably the same search as what the search icon provides currently?)
- Hide the ribbon menu in mobile - but where in the hamburger menu did you want to insert the ribbon menu items?

I see a few other small differences, did you want to match these up as well?
- Main header on http://engage.gov.bc.ca/data/ is a bit shorter (the part with the dark-blue background)
- No orange bar in between logo and title (DataBC)

**Comment by Mbrownshoes** [comment]
@h3devin we'd actually like the header to match http://www2.gov.bc.ca/, however, we want it to look like this, where the ribbon items are in the hamburger

<img width="1265" alt="screen shot 2017-03-01 at 12 06 17 pm" src="https://cloud.githubusercontent.com/assets/3362533/23487704/ad9bbbae-fe9c-11e6-9b16-12fbaa54a14f.png">

We also want the search bar to search the BCDC.

For the mobile view we'd like

<img width="468" alt="screen shot 2017-03-01 at 12 06 40 pm" src="https://cloud.githubusercontent.com/assets/3362533/23487716/c841af9a-fe9c-11e6-9c52-5da639b438af.png">

We'd also like to update the background image, we'll have something for you soon

@ll911

**Comment by h3devin** [comment]
So going from those screenshots:
- Shrink the header to be a bit shorter
- Remove the ribbon bar and move the links into the hamburger menu (but where in the hamburger menu?)
- Remove "DataBC" text in the header? (next to the BC Gov logo)

It looks like the Search currently goes to the BCDC.

**Comment by Mbrownshoes** [comment]
@ll911 @h3devin sorry for the lack of detail. 
- yes, the header will be a bit more compressed to match gov.bc.ca
- for the hamburger we'd like our current ribbon items to replace these items highlighted
![screen shot 2017-03-02 at 11 48 13 am](https://cloud.githubusercontent.com/assets/3362533/23524309/ee8478f2-ff3e-11e6-92eb-c53de0c954de.png)
- Keep the Databc text in the header

**Comment by Mbrownshoes** [comment]
@h3devin we'd also like to add a link to our site-usage page https://catalogue.data.gov.bc.ca/data/site-usage/dataset. @ll911 this would probably also have to go in the hamburger

**Comment by ll911** [comment]
We can expose both site usage and dataset usage
https://catalogue.data.gov.bc.ca/data/site-usage
https://catalogue.data.gov.bc.ca/data/site-usage/dataset

**Comment by h3devin** [comment]
@Mbrownshoes @ll911 

Here's a new branch for the theme updates.  https://github.com/HighwayThree/data-fp/tree/new-theme

In summary:
- Moved ribbon links into dropdown menu, removed ribbon bar
- Shrunk header to match gov style
- Added links to site and dataset usage

Not sure how we wanted to handle this - is a pull request into the master branch good?

Something I noted while doing the updates was that prod seems to be using an out-of-date version of master.  For example in the latest master branch, the mobile version of the logo is removed from the header but production (https://data.gov.bc.ca/) still has it.  I updated the style assuming we were going to keep these changes in master, but if not let me know and I can revert some of the changes to accommodate.

**Comment by ll911** [comment]
yup, you can pull with master, current prod using release tag.

**Comment by Mbrownshoes** [comment]
@h3devin.  just a couple more tweeks
- Move the search bar and carousel up a bit (since the header is now smaller)
- remove the expandable footer and have it match the blog http://engage.gov.bc.ca/data/
- have the hamburger just include the current links on data.gov to match the style of the blog

**Comment by h3devin** [comment]
@Mbrownshoes Applied those updates in my latest pull request.

**Comment by Mbrownshoes** [comment]
@h3devin nice. just one last change. Please change the search bar to match the main gov page

Replace the text with 'Search the BC Data Catalogue'
<img width="781" alt="screen shot 2017-04-10 at 1 16 49 pm" src="https://cloud.githubusercontent.com/assets/3362533/24880698/3ec26b10-1df0-11e7-868b-0c757ccfd0d1.png">

**Comment by h3devin** [comment]
@Mbrownshoes Style updated.

**Comment by ll911** [comment]
Nice.

**Comment by Mbrownshoes** [comment]
indeed
