### ISSUE TITLE
#42 fine and tune

### ISSUE THREAD

**Issue by ll911** [bcgov/data-fp#44]
#42 fine and tune
@Mbrownshoes 
1. can you provide the context for site description, so @h3devin can include in ```_config.template.yml``` file, this is required by google search and SEO
2. can you confirm the location for "Datasets Usage" tab, I thought it should beside the Catalogue, last tab should be the "Contact Us"

@h3devin seems the site title text doesn't align with the Province logo in the new header.

**Comment by Mbrownshoes** [comment]
@ll911 how about- 1) description: BC Government site to facilitate access and encourage the use of government data. Search the BC Data Catalogue and explore visualizations and links to featured datasets. 
2) I think it makes most sense to have the link next to the catalogue tab

**Comment by Mbrownshoes** [comment]
@h3devin please update the description in the yml file and move the 'Datasets Usage' link next to the catalogue tab

**Comment by h3devin** [comment]
@Mbrownshoes This was done in https://github.com/bcgov/data-fp/pull/45
