### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/data-fp#49]
when entering a search term and then selecting the magnifying glass to search, the following message appears

![screen shot 2017-06-21 at 3 19 22 pm](https://user-images.githubusercontent.com/3362533/27410311-9a8db4ca-569b-11e7-9693-6e71db46355f.png)
@ll911

**Comment by h3devin** [comment]
How should the search function when the magnifying glass icon is pressed?  Should it refresh the autocomplete results, or send a search to the data catalogue?

**Comment by ll911** [comment]
@h3devin should be the same behaviour as the search bar.

**Comment by h3devin** [comment]
Shouldn't be too complicated then.  1 - 2 hours for a fix.
